In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("survey lung cancer.csv")
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [3]:
data.shape

(309, 16)

In [4]:
data.dtypes

GENDER                   object
AGE                       int64
SMOKING                   int64
YELLOW_FINGERS            int64
ANXIETY                   int64
PEER_PRESSURE             int64
CHRONIC DISEASE           int64
FATIGUE                   int64
ALLERGY                   int64
WHEEZING                  int64
ALCOHOL CONSUMING         int64
COUGHING                  int64
SHORTNESS OF BREATH       int64
SWALLOWING DIFFICULTY     int64
CHEST PAIN                int64
LUNG_CANCER              object
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [6]:
# Checking for null values
data.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [8]:
data.replace({"LUNG_CANCER":{'YES':0,'NO':1}},inplace=True) # Converting YES and NO to 1 and 2
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,0
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,0
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,1
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,1

In [9]:
data.replace({"GENDER":{'M':0,'F':1}},inplace=True) # Converting M to 0 and F to 1
data.head(5)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,0
1,0,74,2,1,1,1,2,2,2,1,1,1,2,2,2,0
2,1,59,1,1,1,2,1,2,1,2,1,2,2,1,2,1
3,0,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1
4,1,63,1,2,1,1,1,1,1,2,1,2,2,1,1,1

In [10]:
data['LUNG_CANCER'].value_counts()

0    270
1     39
Name: LUNG_CANCER, dtype: int64

In [11]:
x = data.drop(["LUNG_CANCER"],axis=1)
x.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
0,0,69,1,2,2,1,1,2,1,2,2,2,2,2,2
1,0,74,2,1,1,1,2,2,2,1,1,1,2,2,2
2,1,59,1,1,1,2,1,2,1,2,1,2,2,1,2
3,0,63,2,2,2,1,1,1,1,1,2,1,1,2,2
4,1,63,1,2,1,1,1,1,1,2,1,2,2,1,1

In [13]:
y = data['LUNG_CANCER']
y

0      0
1      0
2      1
3      1
4      1
      ..
304    0
305    0
306    0
307    0
308    0
Name: LUNG_CANCER, Length: 309, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
# separating into train and testing
X_train, X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
# scaling the data 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
X_train

array([[-0.93338744, -1.39514731,  0.87423436, ...,  0.71787006,
        -0.86704847,  0.91830473],
       [-0.93338744, -1.14705416, -1.14385804, ...,  0.71787006,
        -0.86704847,  0.91830473],
       [-0.93338744,  0.58959789, -1.14385804, ...,  0.71787006,
        -0.86704847, -1.08896313],
       ...,
       [ 1.07136646, -0.15468156,  0.87423436, ...,  0.71787006,
         1.15333806, -1.08896313],
       [ 1.07136646,  0.96173762,  0.87423436, ...,  0.71787006,
        -0.86704847, -1.08896313],
       [-0.93338744,  0.21745817,  0.87423436, ...,  0.71787006,
        -0.86704847,  0.91830473]])

In [17]:
X_test

array([[ 1.07136646, -0.15468156, -1.14385804,  0.91830473,  1.04557178,
         1.01222041, -0.96420304, -1.55902391,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096, -1.39300976,  1.15333806, -1.08896313],
       [-0.93338744, -1.14705416,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [-0.93338744,  1.33387734, -1.14385804, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
         0.91830473,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744,  0.96173762, -1.14385804,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976,  1.15333806,  0.91830473],
       [-0.93338744,  0.34150474, -1.14385804,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
         0.91830473,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [ 1.07136646,  0.71364447, -1.14385804, -1.08896313,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473, -1.18239513, -1.39300976,  1.15333806, -1.08896313],
       [-0.93338744, -1.27110073,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [-0.93338744,  1.20983077,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712, -0.96420304,  0.64142698,  0.93338744,  0.91830473,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  0.21745817,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304,  0.64142698,  0.93338744, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006, -0.86704847,  0.91830473],
       [-0.93338744, -0.03063498,  0.87423436,  0.91830473, -0.95641449,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744, -0.52682128,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712, -0.96420304, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976, -0.86704847, -1.08896313],
       [-0.93338744,  0.71364447,  0.87423436, -1.08896313, -0.95641449,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
         0.91830473,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [ 1.07136646, -1.02300758,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391, -1.07136646,  0.91830473,
         0.91830473, -1.18239513,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744, -0.52682128,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712, -0.96420304, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976, -0.86704847,  0.91830473],
       [-0.93338744, -0.52682128,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391, -1.07136646, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646, -0.15468156,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698,  0.93338744, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006, -0.86704847, -1.08896313],
       [ 1.07136646,  1.58197049, -1.14385804,  0.91830473, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006, -0.86704847, -1.08896313],
       [-0.93338744,  1.58197049,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391, -1.07136646, -1.08896313,
        -1.08896313, -1.18239513, -1.39300976, -0.86704847,  0.91830473],
       [ 1.07136646,  1.58197049, -1.14385804,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698,  0.93338744, -1.08896313,
         0.91830473,  0.84574096, -1.39300976, -0.86704847, -1.08896313],
       [-0.93338744, -2.26347333, -1.14385804,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313, -1.18239513,  0.71787006,  1.15333806,  0.91830473],
       [ 1.07136646, -0.27872813,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698, -1.07136646, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006, -0.86704847, -1.08896313],
       [ 1.07136646,  1.20983077,  0.87423436,  0.91830473,  1.04557178,
         1.01222041, -0.96420304,  0.64142698, -1.07136646, -1.08896313,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744,  0.58959789, -1.14385804, -1.08896313, -0.95641449,
         1.01222041, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  1.08578419,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304, -1.55902391,  0.93338744, -1.08896313,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  1.70601706, -1.14385804,  0.91830473,  1.04557178,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [ 1.07136646,  0.83769104, -1.14385804, -1.08896313,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473, -1.18239513, -1.39300976,  1.15333806, -1.08896313],
       [-0.93338744, -0.27872813,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304, -1.55902391, -1.07136646, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646,  0.58959789,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391, -1.07136646, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744, -0.77491443,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  0.21745817,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [ 1.07136646, -1.64324046, -1.14385804, -1.08896313, -0.95641449,
         1.01222041,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
         0.91830473,  0.84574096,  0.71787006, -0.86704847, -1.08896313],
       [-0.93338744,  0.09341159,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304, -1.55902391, -1.07136646, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646, -0.03063498,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [-0.93338744, -0.52682128, -1.14385804, -1.08896313, -0.95641449,
         1.01222041, -0.96420304,  0.64142698,  0.93338744,  0.91830473,
         0.91830473, -1.18239513, -1.39300976,  1.15333806, -1.08896313],
       [ 1.07136646, -0.40277471, -1.14385804,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096,  0.71787006,  1.15333806, -1.08896313],
       [ 1.07136646,  2.32624994, -1.14385804,  0.91830473,  1.04557178,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744,  1.20983077,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596,  0.64142698, -1.07136646,  0.91830473,
         0.91830473,  0.84574096,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744, -0.65086786,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391, -1.07136646, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [-0.93338744, -0.40277471, -1.14385804,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646, -0.77491443, -1.14385804,  0.91830473,  1.04557178,
         1.01222041, -0.96420304, -1.55902391,  0.93338744, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646,  1.83006364, -1.14385804,  0.91830473,  1.04557178,
         1.01222041,  1.03712596,  0.64142698, -1.07136646,  0.91830473,
         0.91830473, -1.18239513, -1.39300976, -0.86704847, -1.08896313],
       [-0.93338744,  1.20983077,  0.87423436,  0.91830473,  1.04557178,
         1.01222041,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646,  1.20983077,  0.87423436,  0.91830473,  1.04557178,
         1.01222041, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806, -1.08896313],
       [-0.93338744,  1.83006364,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744,  0.91830473,
        -1.08896313, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646, -1.89133361,  0.87423436,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006, -0.86704847, -1.08896313],
       [-0.93338744,  0.21745817, -1.14385804,  0.91830473,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  0.96173762, -1.14385804,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698,  0.93338744, -1.08896313,
         0.91830473,  0.84574096, -1.39300976, -0.86704847, -1.08896313],
       [ 1.07136646, -1.39514731,  0.87423436,  0.91830473,  1.04557178,
         1.01222041, -0.96420304,  0.64142698,  0.93338744, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006,  1.15333806, -1.08896313],
       [ 1.07136646,  0.09341159, -1.14385804, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698, -1.07136646, -1.08896313,
        -1.08896313, -1.18239513,  0.71787006, -0.86704847, -1.08896313],
       [-0.93338744, -0.77491443,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712, -0.96420304,  0.64142698,  0.93338744,  0.91830473,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  1.20983077, -1.14385804,  0.91830473, -0.95641449,
        -0.98792712, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
         0.91830473,  0.84574096,  0.71787006, -0.86704847, -1.08896313],
       [ 1.07136646,  1.58197049, -1.14385804,  0.91830473,  1.04557178,
         1.01222041, -0.96420304, -1.55902391,  0.93338744,  0.91830473,
        -1.08896313,  0.84574096, -1.39300976,  1.15333806, -1.08896313],
       [ 1.07136646,  0.34150474,  0.87423436,  0.91830473,  1.04557178,
         1.01222041, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806, -1.08896313],
       [-0.93338744, -0.77491443, -1.14385804, -1.08896313, -0.95641449,
        -0.98792712,  1.03712596,  0.64142698,  0.93338744, -1.08896313,
         0.91830473,  0.84574096,  0.71787006, -0.86704847,  0.91830473],
       [ 1.07136646,  1.45792392,  0.87423436,  0.91830473,  1.04557178,
         1.01222041, -0.96420304,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313,  0.84574096,  0.71787006,  1.15333806, -1.08896313],
       [-0.93338744,  1.95411021, -1.14385804,  0.91830473, -0.95641449,
         1.01222041,  1.03712596,  0.64142698, -1.07136646,  0.91830473,
        -1.08896313, -1.18239513,  0.71787006,  1.15333806,  0.91830473],
       [-0.93338744,  0.21745817, -1.14385804,  0.91830473,  1.04557178,
         1.01222041, -0.96420304, -1.55902391,  0.93338744, -1.08896313,
         0.91830473, -1.18239513, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646,  1.33387734,  0.87423436,  0.91830473,  1.04557178,
        -0.98792712,  1.03712596, -1.55902391,  0.93338744, -1.08896313,
         0.91830473, -1.18239513, -1.39300976, -0.86704847, -1.08896313],
       [-0.93338744,  0.83769104, -1.14385804,  0.91830473,  1.04557178,
        -0.98792712, -0.96420304, -1.55902391, -1.07136646,  0.91830473,
         0.91830473,  0.84574096,  0.71787006,  1.15333806, -1.08896313],
       [-0.93338744, -1.02300758,  0.87423436, -1.08896313, -0.95641449,
        -0.98792712, -0.96420304, -1.55902391,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976, -0.86704847, -1.08896313],
       [ 1.07136646, -0.03063498,  0.87423436, -1.08896313, -0.95641449,
         1.01222041, -0.96420304,  0.64142698,  0.93338744,  0.91830473,
         0.91830473,  0.84574096, -1.39300976,  1.15333806,  0.91830473],
       [ 1.07136646, -0.77491443, -1.14385804, -1.08896313,  1.04557178,
         1.01222041,  1.03712596,  0.64142698,  0.93338744,  0.91830473,
         0.91830473, -1.18239513,  0.71787006,  1.15333806,  0.91830473]])

#  KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier
# determining the best k-value
counter=1
for k in range(1,11):
    knn_new = KNeighborsClassifier(n_neighbors=k)
    knn_new.fit(X_train,Y_train)
    print(counter,"  ","Accuracy Score: %",knn_new.score(X_test,Y_test)*100) 
    counter +=1

1    Accuracy Score: % 96.7741935483871
2    Accuracy Score: % 96.7741935483871
3    Accuracy Score: % 95.16129032258065
4    Accuracy Score: % 95.16129032258065
5    Accuracy Score: % 93.54838709677419
6    Accuracy Score: % 95.16129032258065
7    Accuracy Score: % 95.16129032258065
8    Accuracy Score: % 95.16129032258065
9    Accuracy Score: % 95.16129032258065
10    Accuracy Score: % 95.16129032258065

In [61]:
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=2)
k_fit=knn.fit(X_train, Y_train)
k_prediction = k_fit.predict(X_test)

print("Accuracy on test data for k=2 is",accuracy_score(k_prediction,Y_test))

Accuracy on test data for k=2 is 0.967741935483871

In [62]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, Y_train)
prediction = knn.predict(X_test)

print("Accuracy on test data for k=2 is",knn.score(X_test,Y_test))

Accuracy on test data for k=2 is 0.967741935483871

# DecisionTreeClassifier

In [63]:
from sklearn.tree import DecisionTreeClassifier
clf = tree.DecisionTreeClassifier()
clf.fit(X_train,Y_train)

DecisionTreeClassifier()

In [64]:
clf_pred = clf.predict(X_test)

In [70]:
print("Test Accuracy of Decision Tree Model is" ,accuracy_score(Y_test, clf_pred))

Test Accuracy of Decision Tree Model is 0.9516129032258065

# Logistic Regression

In [66]:
from sklearn.linear_model import LogisticRegression

In [67]:
logistic = LogisticRegression()
logistic.fit(X_train,Y_train)

LogisticRegression()

In [68]:
logistic_pred= logistic.predict(X_test)

In [69]:
print("Test Accuracy of Logistic Regression Model is",accuracy_score(Y_test,logistic_pred))

Test Accuracy of Logistic Regression Model is 0.967741935483871